import AppKit
import Foundation

public actor SystemPasteboardClient: PasteboardClient {
    private let pasteboard: NSPasteboard

    public init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    public func snapshot() async throws -> PasteboardSnapshot {
        let items: [PasteboardItemSnapshot] = (pasteboard.pasteboardItems ?? []).map { item in
            var representations: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    representations[type.rawValue] = data
                }
            }
            return PasteboardItemSnapshot(representationsByType: representations)
        }

        return PasteboardSnapshot(items: items, changeCount: pasteboard.changeCount)
    }

    public func clearAndWritePlainText(_ text: String, marker: PasteboardMarker) async throws -> PasteboardWriteResult {
        let failedMutationChangeCount = pasteboard.clearContents()

        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString(marker.uuid.uuidString, forType: NSPasteboard.PasteboardType(PasteboardMarker.pasteboardType))
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        item.setString("1", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))

        guard pasteboard.writeObjects([item]) else {
            throw PasteboardWriteFailure(failedMutationChangeCount: failedMutationChangeCount)
        }

        return PasteboardWriteResult(changeCount: pasteboard.changeCount)
    }

    public func containsMarker(_ marker: PasteboardMarker) async throws -> Bool {
        let markerType = NSPasteboard.PasteboardType(PasteboardMarker.pasteboardType)
        return pasteboard.pasteboardItems?.contains { item in
            item.string(forType: markerType) == marker.uuid.uuidString
        } ?? false
    }

    public func currentChangeCount() async -> Int {
        pasteboard.changeCount
    }

    public func restore(
        _ snapshot: PasteboardSnapshot,
        ifCurrentChangeCountMatches expectedChangeCount: Int
    ) async throws -> Bool {
        guard pasteboard.changeCount == expectedChangeCount else {
            return false
        }

        pasteboard.clearContents()
        let items = snapshot.items.map { snapshotItem in
            let item = NSPasteboardItem()
            for (type, data) in snapshotItem.representationsByType {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }

        guard pasteboard.writeObjects(items) else {
            throw InsertionFailureReason.pasteboardWriteFailed
        }
        return true
    }
}
